otel:
  exclusions:
    - /health
  traces:
    exporter: jaeger,logging,otlp
micronaut:
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: ${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}
  metrics:
    export:
      prometheus:
        enabled: true
        descriptions: true
        step: PT1M
    enabled: true
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
elasticsearch.httpHosts: http://localhost:9200,http://127.0.0.2:9200
micrometer:
  observation:
    http:
      server:
        enabled: true
      client:
        enabled: true
