#otel:
#  exclusions:
#    - /health
#  traces:
#    exporter: jaeger,logging,otlp
micronaut:
  application:
    name: servicebus-controller
  security:
    enabled: false
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: ${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}
  metrics:
    export:
      prometheus:
        enabled: true
        descriptions: true
        step: PT1M
    enabled: true
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**

micrometer:
  observation:
    http:
      server:
        enabled: true
      client:
        enabled: true

endpoints:
  all:
    enabled: true
    sensitive: false
  health:
    details-visible: ANONYMOUS
  loggers:
    write-sensitive: false
  prometheus:
    enabled: true
